name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  test_jobs:
    name: Executando teste job
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Executando um comando simples
        run: echo "Teste do job realizado com sucesso"
    